/**
1-4 진행 사항:
데이터베이스에 대한 정의를 작성
2-1 진행 사항:
게시판 데이터베이스를 정의
*/
CREATE DATABASE login_test;

CREATE TABLE users(
    id VARCHAR(45) NOT NULL PRIMARY KEY,
    password VARCHAR(100) NOT NULL,
    token VARCHAR(500),
    email VARCHAR(50) NOT NULL,
    phoneNumber VARCHAR(15) NOT NULL,
    adress VARCHAR(100) NOT NULL,
    lawyer VARCHAR(10) NOT NULL
);

ALTER TABLE users ADD COLUMN phoneNumber VARCHAR(15) NOT NULL;
ALTER TABLE users ADD COLUMN email VARCHAR(50) NOT NULL;
ALTER TABLE users ADD COLUMN adress VARCHAR(100) NOT NULL;
ALTER TABLE users ADD COLUMN lawyer VARCHAR(10) NOT NULL;

SELECT * FROM users;

CREATE DATABASE post_test;

CREATE TABLE posts(
    Post_Num INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    Post_ID VARCHAR(45) NOT NULL, 
    Post_Title VARCHAR(100) NOT NULL, 
    Post_Date DATE NOT NULL TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    Post_Tag VARCHAR(10) NOT NULL,
    Post_Content VARCHAR(1000) NOT NULL
);